version: '3.7'

services:
  golanggg:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-golang
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - "8181:8181"
    networks:
      - app-network

  web-server:
    image: nginx:1.17.10-alpine
    container_name: web-server
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/blowstack
    ports:
      - 80:80
    networks:
      - app-network
    depends_on:
      - golanggg
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  web-root: